//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPracticum
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastName
    {
        public LastName()
        {
            this.User = new HashSet<User>();
        }
    
        public string LName { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
