//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBPracticum
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Relation1 = new HashSet<Relation>();
            this.Relation2 = new HashSet<Relation>();
        }
    
        public System.Guid Id { get; set; }
        public string Email { get; set; }
        public byte[] Photo { get; set; }
        public System.DateTime BirthDateBDate { get; set; }
        public string FirstNameFName { get; set; }
        public string LastNameLName { get; set; }
    
        public virtual BirthDate BirthDate { get; set; }
        public virtual FirstName FirstName { get; set; }
        public virtual ICollection<Relation> Relation1 { get; set; }
        public virtual ICollection<Relation> Relation2 { get; set; }
        public virtual LastName LastName { get; set; }
    }
}
